# Generated by Django 3.1.7 on 2021-03-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20210311_0708'),
        ('booking', '0007_prebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebooking',
            name='seat_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seats'),
        ),
    ]
