# Generated by Django 3.1.7 on 2021-03-12 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20210311_0708'),
        ('booking', '0008_auto_20210311_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prebooking',
            old_name='seat_id',
            new_name='prebookingseat_id',
        ),
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together={('show_id', 'seat_id')},
        ),
        migrations.CreateModel(
            name='PreBookingSelectedSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prebooking_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking.prebooking')),
                ('prebookingseat_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cinema.seats')),
                ('show_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.show')),
            ],
        ),
    ]
