# Generated by Django 3.1.7 on 2021-03-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20210311_0708'),
        ('booking', '0009_auto_20210312_0446'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together={('booking_id', 'show_id', 'seat_id')},
        ),
    ]
