# Generated by Django 3.1.7 on 2021-03-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210312_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prebooking',
            name='prebookingseat_id',
        ),
    ]
