# Generated by Django 3.1.7 on 2021-03-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20210311_0708'),
        ('booking', '0011_remove_prebooking_prebookingseat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedseat',
            old_name='seat_id',
            new_name='seats_ids',
        ),
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together={('booking_id', 'show_id', 'seats_ids')},
        ),
    ]
