# Generated by Django 3.1.7 on 2021-03-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210312_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prebookingselectedseats',
            old_name='prebookingseat_id',
            new_name='seat_id',
        ),
    ]
