# Generated by Django 3.1.7 on 2021-03-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20210311_0708'),
        ('booking', '0013_auto_20210312_0700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prebookingselectedseats',
            unique_together={('seat_id', 'show_id')},
        ),
    ]
