# Generated by Django 3.1.7 on 2021-03-12 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_prebooking_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebookingselectedseats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
