# Generated by Django 3.1.7 on 2021-03-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_prebookingselectedseats_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prebookingselectedseats',
            unique_together=set(),
        ),
    ]
