# Generated by Django 3.1.7 on 2021-03-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.AutoField(primary_key=True, serialize=False)),
                ('cinem_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CinemasInCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.city')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('cinemahall_id', models.AutoField(primary_key=True, serialize=False)),
                ('cinemahall_name', models.CharField(max_length=50)),
                ('cinama_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
        ),
    ]
