# Generated by Django 3.1.7 on 2021-03-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinema_cinemahall_cinemasincity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('seat_row', models.CharField(max_length=1)),
                ('cinemahall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall')),
            ],
        ),
    ]
