# Generated by Django 3.1.7 on 2021-03-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20210302_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='city_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cinema.city'),
            preserve_default=False,
        ),
    ]
