# Generated by Django 3.1.7 on 2021-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20210306_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='show_id',
        ),
    ]
