# Generated by Django 3.1.7 on 2021-03-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_cinemahall_show_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cinemahall_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall'),
        ),
    ]
