# Generated by Django 3.1.7 on 2021-03-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_startdate', models.DateTimeField()),
                ('movie_enddate', models.DateTimeField()),
            ],
        ),
    ]
